### ISSUE TITLE
Stackdriver Trace Dropped Labels?

### ISSUE THREAD

**Issue by bzon** [census-ecosystem/opencensus-go-exporter-stackdriver#115]
My app runs in GKE. Some exported **span annotation data attributes** (from span.Annotate) in Stackdriver are dropped. This doesn't happen in Jaeger. Is this an issue with Stackdriver itself or is it the Stackdriver exporter Go library?

<img width="235" alt="Screen Shot 2019-03-24 at 12 20 33 AM" src="https://user-images.githubusercontent.com/19391568/54872847-240c5a80-4dcb-11e9-937d-a3e95f60e038.png">

**Comment by songy23** [comment]
The Stackdriver trace exporter has some limits on the number of annotations/attributes/message events that you can send. If the number goes above the limit, some annotations/attributes/message events will be dropped and the count will be recorded. For example:
https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/88d38dcdd3435d86fe1eaedce238ce44d3b852f5/trace_proto.go#L86-L89

I believe Jaeger exporter doesn't have these limits and that's why you didn't see the dropped labels count on Jaeger.

**Comment by songy23** [comment]
BTW those limits are imposed by Stackdriver trace APIs. See https://cloud.google.com/trace/docs/quotas:

> Maximum number of label/attributes per span   32

Maximum number of label/attributes per span | 32
-- | --




Maximum number of label/attributes per span | 32
-- | --

**Comment by bzon** [comment]
Got it. Thanks! 🤦‍♂️
