### ISSUE TITLE
Remove opencensus_task label [was: High cardinality of opencensus_task label]

### ISSUE THREAD

**Issue by ramonza** [census-ecosystem/opencensus-go-exporter-stackdriver#16]
Added in https://github.com/census-instrumentation/opencensus-go/pull/252

This label seems like it will have high cardinality and simultaneously not be very useful. Is there a way we can avoid this? Does exporting deltas instead of cumulative help? Or if we know for sure that the monitored resource is unique, can we provide an option to disable setting this label?

/cc @songy23

**Comment by songy23** [comment]
Background:

We added this task label before, since it's possible that `MonitoredResource` alone cannot uniquely identify Stackdriver `TimeSeries` (e.g multiple processes running on one GCE instance), and this could [cause errors](https://github.com/census-instrumentation/opencensus-java/issues/865):
`Points must be written in order. One or more of the points specified was older than the most recent stored point.: timeSeries[0-2]`

There's one section in [README](https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/stats/stackdriver#what-is-opencensus_task-metric-label-) that also explained this.

Back to the questions:

> Is there a way we can avoid this?

Currently the task label will be added to Stackdriver stats exporter in C++, Java and Go by default, and we don't have an option to disable it yet.

> Does exporting deltas instead of cumulative help?

Unfortunately Stackdriver doesn't allow custom metrics to be of type `Delta`.

> Or if we know for sure that the monitored resource is unique, can we provide an option to disable setting this label?

This could be an option. The task label is not necessary if `MonitoredResource` can uniquely identify the exported stats. We can let the user choose whether they want this label or not.

Since Stackdriver has extended the definition of [MonitoredResourceMetadata](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#monitoredresourcemetadata) recently, another option is to have the task label as an optional `MonitoredResourceMetadata.userLabel`.

**Comment by ramonza** [comment]
Plan of record is to replace the opencensus_task label with userLabels in the default MonitoredResourceMetadata, and users will also be able to override the default MonitoredResourceMetadata with [Options.Resource](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/stackdriver.go#L79).

**Comment by songy23** [comment]
Please note that this is a breaking change, since we're modifying the definition of previous metrics (there's one less label in the metrics). Users of Stackdriver exporter may need to delete the previous metric definitions to avoid errors.
