### ISSUE TITLE
Golang Metrics End-to-End coupla bugs

### ISSUE THREAD

**Issue by DazWilkin** [census-ecosystem/opencensus-go-exporter-stackdriver#99]
https://opencensus.io/quickstart/go/metrics/#end-to-end-code

1. Views are registered twice: LL62-66 and LL94-97
1. `startTime` referenced but not defined, perhaps before L118:
```
startTime:=time.Now()
```

**Comment by mattwelke** [comment]
Looks like these issues are still present in the end to end docs example.

**Comment by dashpole** [comment]
For issues with the opencensus website, it is probably best to open an issue there.  This repository tracks issues related to the stackdriver exporters.

The code that is used in the website appears to be an older version of https://github.com/census-instrumentation/opencensus-go/blob/master/examples/quickstart/stats.go, so that would probably be a good place to start.
